# V5.4.1 E6.b — playback 8ch matrix 16x8 + mic cross-pipeline tap
#
# Architecture E6.b PIPE 2 play (extension de pipe-matrix-playback.m4 E6.a) :
#
#   PCM 1 (ASIO play 8ch) → B0(8ch) → deinterleave_8_a (instance 0) → B1..B8 (8 mono ASIO)
#                                                                      ↓ (mixer16 sources 0..7)
#                                                          mixer16 (16x8 identity) → B10..B17 (8 mono)
#                                                                      ↑ (mixer16 sources 8..15)
#   B_mic_xport(8ch from PIPE 1) → deinterleave_8_b (instance 1) → B20..B27 (8 mono mics)
#                                                                      ↓
#                                                                interleave_8 → B100(8ch) → SAI7 TX
#
# Identity matrix par défaut : sources [0..7] (ASIO play) → sinks 0..7 passthrough,
# sources [8..15] (mics) gain=0 (muet). User peut activer mic via amixer cset (E6.c).
#
# Cross-pipeline tap : le buffer source des mics vient de PIPE 1 (post-pga 8ch après tee_1to2).
# La connexion se fait via SectionGraph dans le top-level E6b.m4 :
#   dapm(N_DEINTERLEAVE_8_INSTANCE_1_PIPE_2, BUF_PIPE_1_INDEX_5)
#
# F++ auto-detection lock channels=1 sur tous les buffers mono branchés (B1..B8 + B20..B27 + B10..B17).
# tee_1to2 cross-pipeline sink overrun_permitted (déjà géré par tee_1to2_trigger).

include(`utils.m4')
include(`buffer.m4')
include(`pcm.m4')
include(`dai.m4')
include(`pipeline.m4')
include(`mixercontrol.m4')
include(`bytecontrol.m4')
include(`deinterleave_8.m4')
include(`interleave_8.m4')
include(`mixer16.m4')

#
# Components
#

W_PCM_PLAYBACK(PCM_ID, ASIO OUT, 0, 2, SCHEDULE_CORE)

# deinterleave_8 instance 0 : ASIO play 8ch → 8 mono
W_DEINTERLEAVE_8(0, PIPELINE_FORMAT, 2, 2, SCHEDULE_CORE)

# deinterleave_8 instance 1 : mic tap 8ch (cross-pipeline) → 8 mono
W_DEINTERLEAVE_8(1, PIPELINE_FORMAT, 2, 2, SCHEDULE_CORE)

# mixer16 16x8 identity matrix
W_MIXER16(0, PIPELINE_FORMAT, 2, 2, SCHEDULE_CORE, ` ')

# interleave_8 : 8 mono → 1×8ch
W_INTERLEAVE_8(0, PIPELINE_FORMAT, 2, 2, SCHEDULE_CORE)

#
# Buffers
#

# B0 : PCM playback → deinterleave_8_a (8ch ASIO play side)
W_BUFFER(0, COMP_BUFFER_SIZE(2,
	COMP_SAMPLE_SIZE(PIPELINE_FORMAT), 8,
	COMP_PERIOD_FRAMES(PCM_MAX_RATE, SCHEDULE_PERIOD)),
	PLATFORM_HOST_MEM_CAP)

# B100 : interleave_8 → SAI TX (8ch DAI side)
W_BUFFER(100, COMP_BUFFER_SIZE(DAI_PERIODS,
	COMP_SAMPLE_SIZE(PIPELINE_FORMAT), 8,
	COMP_PERIOD_FRAMES(PCM_MAX_RATE, SCHEDULE_PERIOD)),
	PLATFORM_DAI_MEM_CAP)

# B1..B8 : mono ASIO play (deinterleave_8_a sinks → mixer16 sources 0..7)
W_BUFFER(1, COMP_BUFFER_SIZE(2,
	COMP_SAMPLE_SIZE(PIPELINE_FORMAT), 1,
	COMP_PERIOD_FRAMES(PCM_MAX_RATE, SCHEDULE_PERIOD)),
	PLATFORM_HOST_MEM_CAP)
W_BUFFER(2, COMP_BUFFER_SIZE(2,
	COMP_SAMPLE_SIZE(PIPELINE_FORMAT), 1,
	COMP_PERIOD_FRAMES(PCM_MAX_RATE, SCHEDULE_PERIOD)),
	PLATFORM_HOST_MEM_CAP)
W_BUFFER(3, COMP_BUFFER_SIZE(2,
	COMP_SAMPLE_SIZE(PIPELINE_FORMAT), 1,
	COMP_PERIOD_FRAMES(PCM_MAX_RATE, SCHEDULE_PERIOD)),
	PLATFORM_HOST_MEM_CAP)
W_BUFFER(4, COMP_BUFFER_SIZE(2,
	COMP_SAMPLE_SIZE(PIPELINE_FORMAT), 1,
	COMP_PERIOD_FRAMES(PCM_MAX_RATE, SCHEDULE_PERIOD)),
	PLATFORM_HOST_MEM_CAP)
W_BUFFER(5, COMP_BUFFER_SIZE(2,
	COMP_SAMPLE_SIZE(PIPELINE_FORMAT), 1,
	COMP_PERIOD_FRAMES(PCM_MAX_RATE, SCHEDULE_PERIOD)),
	PLATFORM_HOST_MEM_CAP)
W_BUFFER(6, COMP_BUFFER_SIZE(2,
	COMP_SAMPLE_SIZE(PIPELINE_FORMAT), 1,
	COMP_PERIOD_FRAMES(PCM_MAX_RATE, SCHEDULE_PERIOD)),
	PLATFORM_HOST_MEM_CAP)
W_BUFFER(7, COMP_BUFFER_SIZE(2,
	COMP_SAMPLE_SIZE(PIPELINE_FORMAT), 1,
	COMP_PERIOD_FRAMES(PCM_MAX_RATE, SCHEDULE_PERIOD)),
	PLATFORM_HOST_MEM_CAP)
W_BUFFER(8, COMP_BUFFER_SIZE(2,
	COMP_SAMPLE_SIZE(PIPELINE_FORMAT), 1,
	COMP_PERIOD_FRAMES(PCM_MAX_RATE, SCHEDULE_PERIOD)),
	PLATFORM_HOST_MEM_CAP)

# B10..B17 : mono mixer16 sinks → interleave_8 sources
W_BUFFER(10, COMP_BUFFER_SIZE(2,
	COMP_SAMPLE_SIZE(PIPELINE_FORMAT), 1,
	COMP_PERIOD_FRAMES(PCM_MAX_RATE, SCHEDULE_PERIOD)),
	PLATFORM_HOST_MEM_CAP)
W_BUFFER(11, COMP_BUFFER_SIZE(2,
	COMP_SAMPLE_SIZE(PIPELINE_FORMAT), 1,
	COMP_PERIOD_FRAMES(PCM_MAX_RATE, SCHEDULE_PERIOD)),
	PLATFORM_HOST_MEM_CAP)
W_BUFFER(12, COMP_BUFFER_SIZE(2,
	COMP_SAMPLE_SIZE(PIPELINE_FORMAT), 1,
	COMP_PERIOD_FRAMES(PCM_MAX_RATE, SCHEDULE_PERIOD)),
	PLATFORM_HOST_MEM_CAP)
W_BUFFER(13, COMP_BUFFER_SIZE(2,
	COMP_SAMPLE_SIZE(PIPELINE_FORMAT), 1,
	COMP_PERIOD_FRAMES(PCM_MAX_RATE, SCHEDULE_PERIOD)),
	PLATFORM_HOST_MEM_CAP)
W_BUFFER(14, COMP_BUFFER_SIZE(2,
	COMP_SAMPLE_SIZE(PIPELINE_FORMAT), 1,
	COMP_PERIOD_FRAMES(PCM_MAX_RATE, SCHEDULE_PERIOD)),
	PLATFORM_HOST_MEM_CAP)
W_BUFFER(15, COMP_BUFFER_SIZE(2,
	COMP_SAMPLE_SIZE(PIPELINE_FORMAT), 1,
	COMP_PERIOD_FRAMES(PCM_MAX_RATE, SCHEDULE_PERIOD)),
	PLATFORM_HOST_MEM_CAP)
W_BUFFER(16, COMP_BUFFER_SIZE(2,
	COMP_SAMPLE_SIZE(PIPELINE_FORMAT), 1,
	COMP_PERIOD_FRAMES(PCM_MAX_RATE, SCHEDULE_PERIOD)),
	PLATFORM_HOST_MEM_CAP)
W_BUFFER(17, COMP_BUFFER_SIZE(2,
	COMP_SAMPLE_SIZE(PIPELINE_FORMAT), 1,
	COMP_PERIOD_FRAMES(PCM_MAX_RATE, SCHEDULE_PERIOD)),
	PLATFORM_HOST_MEM_CAP)

# B20..B27 : mono mics (deinterleave_8_b sinks → mixer16 sources 8..15)
W_BUFFER(20, COMP_BUFFER_SIZE(2,
	COMP_SAMPLE_SIZE(PIPELINE_FORMAT), 1,
	COMP_PERIOD_FRAMES(PCM_MAX_RATE, SCHEDULE_PERIOD)),
	PLATFORM_HOST_MEM_CAP)
W_BUFFER(21, COMP_BUFFER_SIZE(2,
	COMP_SAMPLE_SIZE(PIPELINE_FORMAT), 1,
	COMP_PERIOD_FRAMES(PCM_MAX_RATE, SCHEDULE_PERIOD)),
	PLATFORM_HOST_MEM_CAP)
W_BUFFER(22, COMP_BUFFER_SIZE(2,
	COMP_SAMPLE_SIZE(PIPELINE_FORMAT), 1,
	COMP_PERIOD_FRAMES(PCM_MAX_RATE, SCHEDULE_PERIOD)),
	PLATFORM_HOST_MEM_CAP)
W_BUFFER(23, COMP_BUFFER_SIZE(2,
	COMP_SAMPLE_SIZE(PIPELINE_FORMAT), 1,
	COMP_PERIOD_FRAMES(PCM_MAX_RATE, SCHEDULE_PERIOD)),
	PLATFORM_HOST_MEM_CAP)
W_BUFFER(24, COMP_BUFFER_SIZE(2,
	COMP_SAMPLE_SIZE(PIPELINE_FORMAT), 1,
	COMP_PERIOD_FRAMES(PCM_MAX_RATE, SCHEDULE_PERIOD)),
	PLATFORM_HOST_MEM_CAP)
W_BUFFER(25, COMP_BUFFER_SIZE(2,
	COMP_SAMPLE_SIZE(PIPELINE_FORMAT), 1,
	COMP_PERIOD_FRAMES(PCM_MAX_RATE, SCHEDULE_PERIOD)),
	PLATFORM_HOST_MEM_CAP)
W_BUFFER(26, COMP_BUFFER_SIZE(2,
	COMP_SAMPLE_SIZE(PIPELINE_FORMAT), 1,
	COMP_PERIOD_FRAMES(PCM_MAX_RATE, SCHEDULE_PERIOD)),
	PLATFORM_HOST_MEM_CAP)
W_BUFFER(27, COMP_BUFFER_SIZE(2,
	COMP_SAMPLE_SIZE(PIPELINE_FORMAT), 1,
	COMP_PERIOD_FRAMES(PCM_MAX_RATE, SCHEDULE_PERIOD)),
	PLATFORM_HOST_MEM_CAP)

#
# Pipeline graph (PIPE 2 internal — cross-pipeline tap added at top-level)
#
P_GRAPH(pipe-matrix-with-mics-playback, PIPELINE_ID,
	LIST(`		',
	`dapm(N_BUFFER(0), N_PCMP(PCM_ID))',
	`dapm(N_DEINTERLEAVE_8(0), N_BUFFER(0))',
	`dapm(N_BUFFER(1), N_DEINTERLEAVE_8(0))',
	`dapm(N_BUFFER(2), N_DEINTERLEAVE_8(0))',
	`dapm(N_BUFFER(3), N_DEINTERLEAVE_8(0))',
	`dapm(N_BUFFER(4), N_DEINTERLEAVE_8(0))',
	`dapm(N_BUFFER(5), N_DEINTERLEAVE_8(0))',
	`dapm(N_BUFFER(6), N_DEINTERLEAVE_8(0))',
	`dapm(N_BUFFER(7), N_DEINTERLEAVE_8(0))',
	`dapm(N_BUFFER(8), N_DEINTERLEAVE_8(0))',
	`dapm(N_MIXER16(0), N_BUFFER(1))',
	`dapm(N_MIXER16(0), N_BUFFER(2))',
	`dapm(N_MIXER16(0), N_BUFFER(3))',
	`dapm(N_MIXER16(0), N_BUFFER(4))',
	`dapm(N_MIXER16(0), N_BUFFER(5))',
	`dapm(N_MIXER16(0), N_BUFFER(6))',
	`dapm(N_MIXER16(0), N_BUFFER(7))',
	`dapm(N_MIXER16(0), N_BUFFER(8))',
	`dapm(N_BUFFER(20), N_DEINTERLEAVE_8(1))',
	`dapm(N_BUFFER(21), N_DEINTERLEAVE_8(1))',
	`dapm(N_BUFFER(22), N_DEINTERLEAVE_8(1))',
	`dapm(N_BUFFER(23), N_DEINTERLEAVE_8(1))',
	`dapm(N_BUFFER(24), N_DEINTERLEAVE_8(1))',
	`dapm(N_BUFFER(25), N_DEINTERLEAVE_8(1))',
	`dapm(N_BUFFER(26), N_DEINTERLEAVE_8(1))',
	`dapm(N_BUFFER(27), N_DEINTERLEAVE_8(1))',
	`dapm(N_MIXER16(0), N_BUFFER(20))',
	`dapm(N_MIXER16(0), N_BUFFER(21))',
	`dapm(N_MIXER16(0), N_BUFFER(22))',
	`dapm(N_MIXER16(0), N_BUFFER(23))',
	`dapm(N_MIXER16(0), N_BUFFER(24))',
	`dapm(N_MIXER16(0), N_BUFFER(25))',
	`dapm(N_MIXER16(0), N_BUFFER(26))',
	`dapm(N_MIXER16(0), N_BUFFER(27))',
	`dapm(N_BUFFER(10), N_MIXER16(0))',
	`dapm(N_BUFFER(11), N_MIXER16(0))',
	`dapm(N_BUFFER(12), N_MIXER16(0))',
	`dapm(N_BUFFER(13), N_MIXER16(0))',
	`dapm(N_BUFFER(14), N_MIXER16(0))',
	`dapm(N_BUFFER(15), N_MIXER16(0))',
	`dapm(N_BUFFER(16), N_MIXER16(0))',
	`dapm(N_BUFFER(17), N_MIXER16(0))',
	`dapm(N_INTERLEAVE_8(0), N_BUFFER(10))',
	`dapm(N_INTERLEAVE_8(0), N_BUFFER(11))',
	`dapm(N_INTERLEAVE_8(0), N_BUFFER(12))',
	`dapm(N_INTERLEAVE_8(0), N_BUFFER(13))',
	`dapm(N_INTERLEAVE_8(0), N_BUFFER(14))',
	`dapm(N_INTERLEAVE_8(0), N_BUFFER(15))',
	`dapm(N_INTERLEAVE_8(0), N_BUFFER(16))',
	`dapm(N_INTERLEAVE_8(0), N_BUFFER(17))',
	`dapm(N_BUFFER(100), N_INTERLEAVE_8(0))'))

#
# Exports
#
indir(`define', concat(`PIPELINE_PCM_', PIPELINE_ID), ASIO OUT PCM_ID)
indir(`define', concat(`PIPELINE_SOURCE_', PIPELINE_ID), N_BUFFER(100))
# Export du deinterleave_8_b instance pour cross-pipeline binding (vers BUF_PIPE_1_5)
indir(`define', concat(`PIPELINE_MIC_INPUT_DEINT_', PIPELINE_ID), N_DEINTERLEAVE_8(1))

#
# PCM capabilities : 8ch s32le @ 48k
#
PCM_CAPABILITIES(ASIO OUT PCM_ID, CAPABILITY_FORMAT_NAME(PIPELINE_FORMAT),
	PCM_MIN_RATE, PCM_MAX_RATE, 2, PIPELINE_CHANNELS, 2, 16,
	192, 16384, 65536, 65536)
